# Generated by Django 5.2.1 on 2025-05-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Бинарные данные изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
