# Generated by Django 5.2.1 on 2025-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_product_image_data_product_image_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_type',
        ),
    ]
