# Generated by Django 5.2.1 on 2025-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Название товара', max_length=200, verbose_name='Название товара'),
        ),
    ]
