# Generated by Django 5.2.1 on 2025-05-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
